default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: final-spinboard_development

test:
  <<: *default
  database: final-spinboard_test

production:
  <<: *default
  database: final-spinboard_production
  username: emilydowdle1
  password: <%= ENV['FINAL-SPINBOARD_DATABASE_PASSWORD'] %>
